# Generated by Django 5.2 on 2026-02-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="department",
            new_name="subject",
        ),
        migrations.AddField(
            model_name="staff",
            name="batchcode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="branch",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="mode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
