# Generated by Django 5.2 on 2026-02-25 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0003_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teacher.staff"
            ),
        ),
    ]
