# Generated by Django 5.2 on 2026-03-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0004_alter_attendance_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batchcode", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=100)),
                ("trainer", models.CharField(max_length=100)),
                ("mode", models.CharField(max_length=10)),
                ("started", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
