# Generated by Django 5.2 on 2026-03-07 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0005_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="status",
        ),
        migrations.AddField(
            model_name="attendance",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teacher.session",
            ),
        ),
    ]
