# Generated by Django 5.2 on 2026-02-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("phoneno", models.IntegerField(max_length=10)),
                ("country", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
