# Generated by Django 5.2 on 2026-02-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_attendance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attendance",
        ),
    ]
